remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Afeefa Taranum
description: I am a Technical Writer with 6+ years of extensive real-time experience in IT and SaaS, working and documenting work 
processes in software documentation.
